---
#- name: Check if config file exists
#  stat:
#    path: /etc/sv_manager/sv_manager.conf
#  register: config_exists
#
- name: Load config
  include_vars:
    file: "/etc/sv_manager/sv_manager.conf"
  become: yes

- name: Configure lvm
  import_tasks: lvm.yaml
  when: lvm_enabled|bool
  tags:
    config.lvm

- name: Install additional apt packages
  import_tasks: apt_packages.yaml
  tags:
    - config.packages
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install additional yum packages
  import_tasks: yum_packages.yaml
  tags:
    - config.packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create swap
  import_tasks: swap.yaml
  tags:
    - config.swap
  when: swap_file_size_gb | int  > 0

- name: Create ramdisk
  import_tasks: ramdisk.yaml
  tags:
    - config.ramdisk
  when: ramdisk_size_gb | int > 0

- name: Config cpu governor
  import_tasks: cpu_governor.yaml
  tags:
    - config.cpu

- name: Config firewall
  import_tasks: firewall.yaml
  tags:
    - config.firewall
  when:
    use_firewall | bool

- name: Config file2ban
  import_tasks: fail2ban.yaml
  tags:
    - config.fail2ban

- name: Config sysctl
  import_tasks: sysctl.yaml
  tags:
    - config.sysctl

- name: Create ansible user
  import_tasks: ansible_user.yaml
  tags:
    - config.ansible_user
  when:
    - "'local' not in group_names"

- name: Create solana user
  import_tasks: solana_user.yaml
  tags:
    - config.solana_user
    - validator.service.solana
