---

- name: Update apt cache
  become: yes
  yum:
    update_cache: yes

- name: Install additional packages
  become: yes
  yum:
    name:
      - gnupg2
      - python3
      - python3-pip
      - epel-release
      - rsyslog
  tags:
    - config.packages
