---

- name: wait for restarting window
  import_tasks: wait_for_restart_window.yaml
  tags:
    - validator.manage.restart

#- name: restart sys_tuner-service
#  systemd:
#    name: solana-sys-tuner
#    state: restarted
#  tags:
#    - validator.manage.restart.service
#    - validator.manage.restart

- name: stop solana validator service
  systemd:
    name: solana-validator
    state: stopped
  tags:
    - validator.manage.restart.service
    - validator.manage.restart

#- name: run snapshot finder
#  import_tasks: with_snapshot_finder.yaml
#  when: with_snapshot_finder
#  tags:
#    - validator.manage.restart

- name: start solana validator service
  systemd:
    name: solana-validator
    state: started
  tags:
    - validator.manage.restart.service
    - validator.manage.restart