---
set_validator_info: False
cluster_environment: 'mainnet-beta'
cluster_rpc_address: 'https://api.mainnet-beta.solana.com'
validator_service: restarted
swap_file_size_gb: 200
entrypoints:
  - entrypoint.mainnet-beta.solana.com:8001
  - entrypoint2.mainnet-beta.solana.com:8001
  - entrypoint3.mainnet-beta.solana.com:8001
  - entrypoint4.mainnet-beta.solana.com:8001
  - entrypoint5.mainnet-beta.solana.com:8001
known_validators:
  - 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2
  - GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ
  - DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ
  - CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S
validator_metrics_url: 'https://metrics.solana.com:8086,db=mainnet-beta,u=mainnet-beta_write,p=password'
expected_genesis_hash: '5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d'
limit_ledger_size: 50000000
snapshot_interval_slots: 2000
maximum_local_snapshot_age: 3000
validator_version: 1.13.5
extra_params: []

validator_ledger_slot: 179526403
validator_shred_version: 56177
validator_bank_hash: 69p75jzzT1P2vJwVn3wbTVutxHDcWKAgcbjqXvwCVUDE

jito_urls:
  amsterdam:
    block_engine: "https://amsterdam.mainnet.block-engine.jito.wtf"
    relayer: "http://amsterdam.mainnet.relayer.jito.wtf:8100"
    shred_receiver_addr: "74.118.140.240:1002"
  frankfurt:
    block_engine: "https://frankfurt.mainnet.block-engine.jito.wtf"
    relayer: "http://frankfurt.mainnet.relayer.jito.wtf:8100"
    shred_receiver_addr: "145.40.93.84:1002"
  newyork:
    block_engine: "https://ny.mainnet.block-engine.jito.wtf"
    relayer: "http://ny.mainnet.relayer.jito.wtf:8100"
    shred_receiver_addr: "141.98.216.96:1002"
  tokyo:
    block_engine: "https://tokyo.mainnet.block-engine.jito.wtf"
    relayer: "http://tokyo.mainnet.relayer.jito.wtf:8100"
    shred_receiver_addr: "202.8.9.160:1002"
