---

- name: ensure directory exists
  file:
    path: "/etc/sv_manager"
    state: directory
    mode: '0755'

- name: Check if config file exists
  stat:
    path: /etc/sv_manager/sv_manager.conf
  register: config_exists

- name: Load config file
  set_fact:
    config_dict: "{{ lookup('file', '/etc/sv_manager/sv_manager.conf') }}"
  when: config_exists.stat.exists

- name: Update validator_name
  set_fact:
    config_dict: "{{ config_dict | combine( { 'validator_name': validator_name } ) }}"

- name: show new config
  debug:
    var: config_dict

- name: write var to file
  copy:
    content: "{{ config_dict | to_nice_json }}"
    dest: /etc/sv_manager/sv_manager.conf
