---
- name: set facts
  set_fact:
    tmp_install_path: /tmp/validator-build
    docker_builder_name: "validator-builder"
    docker_exec_command: "docker exec -i"
  tags:
    - cli.install
    - cli.make

- name: create download dir
  file:
    path: "{{ tmp_install_path }}"
    state: directory
  become: yes
  tags:
    - cli.install
    - cli.make

- name: install docker
  shell: "wget -qO- https://get.docker.com | bash"
  become: yes
  tags:
    - cli.install
    - cli.make

- name: enable and start docker service
  systemd:
    name: docker
    enabled: true
    state: started
    daemon_reload: true
  become: yes
  tags:
    - cli.install
    - cli.make

- name: check previously running rust container
  shell: "docker ps -a | grep {{ docker_builder_name }}"
  register: container_present
  failed_when: "container_present.rc not in [0,1]"
  become: yes
  tags:
    - cli.install
    - cli.make

- name: kill previously running rust container
  shell: "docker stop {{ docker_builder_name }};docker rm {{ docker_builder_name }}"
  become: yes
  when: container_present.stdout|length > 0
  tags:
    - cli.install
    - cli.make

- name: run docker rust container for build validator binary
  shell: "docker run --name {{ docker_builder_name }} --rm --network host -d -v {{ tmp_install_path }}:{{ tmp_install_path }} -v {{ validator_bin_path }}:{{ validator_bin_path }} rust:bullseye sleep 99999999"
  become: yes
  tags:
    - cli.install
    - cli.make

- name: git load validator source
  shell: "{{ docker_exec_command }} {{ docker_builder_name }} bash -c 'cd {{ tmp_install_path }};git clone {{ github_source }} --recurse-submodules .;git checkout tags/{{ github_source_tag }};git submodule update --init --recursive'"
  become: yes
  tags:
    - cli.install
    - cli.make

- name: install dependencies for build binary
  shell: "{{ docker_exec_command }} {{ docker_builder_name }} bash -c 'rustup component add rustfmt;rustup update;apt update;apt install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler -y'"
  become: yes
  tags:
    - cli.install
    - cli.make

- name: build binary
  shell: "{{ docker_exec_command }} {{ docker_builder_name }} bash -c 'CI_COMMIT=$(git rev-parse HEAD) {{ tmp_install_path }}/scripts/cargo-install-all.sh --validator-only {{ validator_bin_path }}'"
  become: yes
  tags:
    - cli.install
    - cli.make

- name: stop and rm build container
  shell: "docker stop {{ docker_builder_name }}"
  become: yes
  tags:
    - cli.install
    - cli.make

- name: clear tmp install dir
  file:
    path: "{{ tmp_install_path }}"
    state: absent
  tags:
    - cli.install
    - cli.make
