---

- name: Create telegraf config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: 0644
    owner: root
    group: root
    backup: yes
  tags:
    - telegraf.configure

- name: Allow 'telegraf' user to run solana scripts
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^telegraf'
    line: "telegraf ALL=({{ solana_user }}:{{ solana_user }}) NOPASSWD:ALL"
    validate: 'visudo -cf %s'
  tags:
    - telegraf.configure

- name: create telegraf.service.d dir
  file:
    path: /etc/systemd/system/telegraf.service.d
    state: directory
  tags:
    - telegraf.configure

- name: Add solana bin path for telegraf unit file
  template:
    src: 01-telegraf.conf.j2
    dest: /etc/systemd/system/telegraf.service.d/01-telegraf.conf
    mode: 0644
    owner: root
    group: root
    backup: yes
  tags:
    - telegraf.configure

- name: Enable and start telegraf service
  systemd:
    name: telegraf
    daemon_reload: yes
    enabled: yes
    state: restarted
  tags:
    - telegraf.start
    - monitoring.script.library
    - telegraf.configure
  become: yes
