---
#- name: Load config
#  include_vars:
#    file: "/etc/sv_manager/sv_manager.conf"
#  become: true

- name: install additional packages
  import_tasks: packages.yaml
  tags:
    - monitoring

- name: Install telegraf
  import_tasks: install_telegraf.yaml
  tags:
    - monitoring

- name: Install monitoring script
  import_tasks: install_monitoring_script.yaml
  tags:
    - monitoring

- name: Configure telegraf
  import_tasks: configure_telegraf.yaml
  tags:
    - monitoring
