---
- name: Load config
  include_vars:
    file: "/etc/sv_manager/sv_manager.conf"
  become: true

- name: set force install fact
  set_fact:
    force: "{{ force | default('false')  }}"
  tags:
    - cli
    - cli.install
    - cli.update

- name: Load config
  include_vars:
    file: "/etc/sv_manager/sv_manager.conf"

- name: check solana cli installed
  stat:
    path: "{{ env_path }}/solana-install"
  register: solana_exists
  tags:
    - cli
    - cli.install
    - cli.update

- name: install solana cli
  import_tasks: install.yaml
  tags:
    - cli
    - cli.install
  when: force == 'true' or not solana_exists.stat.exists

- name: update solana cli
  import_tasks: update.yaml
  tags:
    - cli
    - cli.update
  when: force != 'true' and solana_exists.stat.exists
