---

- name: cli | get solana snapshot finder
  copy:
    src: files/solana-snapshot-finder
    dest: "{{ env_path }}/solana-snapshot-finder"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    mode: 0755
  tags:
    - cli
    - cli.snapshot-finder

#- name: cli | add python env in solana-snapshot-finder file
#  lineinfile:
#    path: "{{ env_path }}/solana-snapshot-finder"
#    insertbefore: BOF
#    line: "#!/usr/bin/env python3"
#  tags:
#    - cli
#    - cli.snapshot-finder

- name: cli | install requirements
  pip:
    name:
      - requests
      - tqdm
    executable: pip3
  tags:
    - cli
    - cli.snapshot-finder

