---

- name: "{{ role_path|basename }} | Load config"
  include_vars:
    file: "{{ sv_manager_config_path }}"
  ignore_errors: yes

- name: "{{ role_path|basename }} | stop validator service"
  systemd:
    name: "{{ validator_binary }}"
    state: stopped
    enabled: false
  ignore_errors: yes
  tags:
    - validator.remove
    - validator.remove.service
    - validator.remove.service.stop

- name: "{{ role_path|basename }} | Umount mounted fs"
  ansible.posix.mount:
    path: "{{ item }}"
    state: unmounted
  ignore_errors: yes
  with_items:
    - "{{ ramdisk_path }}"
  tags:
    - validator.remove

- name: "{{ role_path|basename }} | Get path to swapfile"
  shell: swapon -s | awk 'NR==2{print $1}'
  register: swap_file
  ignore_errors: yes
  tags:
    - validator.remove

- name: "{{ role_path|basename }} | Stop swap"
  command: swapoff {{ swap_file.stdout }}
  ignore_errors: yes
  tags:
    - validator.remove

- name: "{{ role_path|basename }} | Disable swap in fstab"
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes
  ignore_errors: yes
  tags:
    - validator.remove

- name: "{{ role_path|basename }} | Remove directories and files"
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: yes
  with_items:
    - "{{ mount_base_path }}"
    - "{{ validator_home }}"
    - "{{ swap_file.stdout }}"
    - "/etc/systemd/system/solana-validator.service"
    - "/etc/default/solana-validator"
    - "{{ sv_manager_config_path }}"
  tags:
    - validator.remove
