- name: "{{ role_path|basename }} | Update validator to {{ val_prj }} {% if validator_version is defined %}v{{ validator_version }}{% else %}stable{% endif %}"
  shell: "{{ validator_install_binary }} init -d {{ validator_bin_path }} {% if validator_version is defined %}v{{ validator_version }}{% else %}stable{% endif %}"
  become: yes
  become_user: "{{ validator_user }}"
  environment:
    PATH: "{{ env_path }}"
  tags:
    - cli.update
