---
- name: update solana validator
  hosts: all
  serial: 1
  become: yes
  vars_files:
    - "{{ sv_manager_config_path }}"
  roles:
    - vars_shortcode_mapping
    - name: solana_cli
      tags:
        - cli
        - cli.install
        - cli.update
      when: not jito_validator|bool
    - name: solana_cli_jito
      tags:
        - cli
        - cli.install
        - cli.update
      when: jito_validator|bool
    - solana_validator_restart
