---
- name: update validator
  hosts: all
  serial: 1
  become: yes
  vars_files:
    - "{{ sv_manager_config_path }}"
    - ../vars/{{ val_prj }}.yaml
  roles:
    - vars_shortcode_mapping
    - name: validator_cli
      tags:
        - cli
        - cli.install
        - cli.update
    - validator_restart
