---
- name: "Configure and install {{ val_prj }} validator"
  hosts: all
  become: yes
  vars_files:
    - ../vars/{{ val_prj }}.yaml
  roles:
    - vars_shortcode_mapping
    - validator_config
    - name: configure_ubuntu
      tags:
        - configure.os
    - name: validator_cli
      tags:
        - cli
        - cli.install
        - cli.update
    - name: validator_service_stop
      tags:
        - validator.stop
    - name: validator_bootstrap
      tags:
        - validator_bootstrap
    - monitoring