---
- name: Configure and install solana validator
  hosts: all
  become: yes
  roles:
    - validator_config
    - name: check_node
      tags:
        - check.node
    - name: configure_ubuntu
      tags:
        - configure.os
    - name: validator_cli
      tags:
        - cli
        - cli.install
        - cli.update
    - name: validator_validator_bootstrap
      tags:
        - validator_bootstrap
    - monitoring