---
- name: install solana validator
  hosts: all
  become: yes
  roles:
    - name: check_node
      tags:
        - check.node
    - name: configure_ubuntu
      tags:
        - configure.os
    - name: solana_cli
      tags:
        - cli
        - cli.install
        - cli.update
    - solana_validator_bootstrap
    - monitoring
