---

- name: ensure directory exists
  file:
    path: "/etc/sv_manager"
    state: directory
    mode: '0755'

- name: Check if config file exists
  stat:
    path: "{{ sv_manager_config_path }}"
  register: config_exists

- name: remove config file
  file:
    path: "{{ sv_manager_config_path }}"
    state: absent
  when: config_exists.stat.exists

# - name: show config data
#   debug:
#     msg: "{{ config_data }}"
#   when: config_exists.stat.exists

- name: set dictionary
  set_fact:
    config_dict: "{{ config_data.content | default([]) }}"

- name: create config from template
  set_fact:
    config_dict_template: "{{ lookup('template', 'templates/sv_manager.conf.template') }}"

- name: show present config dictionary
  debug:
    msg: "{{ config_dict }}"

- name: combine with host section
  set_fact:
    config_dict:  "{{ config_dict_template | combine(config_dict) }}"

- name: show new config
  debug:
    var: config_dict

- name: write var to file
  copy:
    content: "{{ config_dict | to_nice_json }}"
    dest: "{{ sv_manager_config_path }}"
