name: Add tags for agent
on:
  push:
    branches:
      - refactor
jobs:
  git-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Git status
        run: git status