name: Add tag for agent
run-name: Add tag for agent
on:
  push:
    branches:
      - agent
jobs:
  git-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git status
        run: git status
      - name: "Get latest tag"
        id: latest_tag
        run: echo "latest_tag=$(git tag --merged agent --sort=-v:refname agent-v* | head -1)" >> $GITHUB_ENV
      - run: | 
          echo "new_tag=$(echo "${{ env.latest_tag }}" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')" >> $GITHUB_ENV
      - run: | 
          echo "${{ env.new_tag }}"
          echo "commit_part=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - run: | 
          git config --global user.email "${{ github.event.commits[0].author.email }}"
          git config --global user.name "${{ github.event.commits[0].author.name }}"
          git tag -d agent-latest
          git push --delete origin agent-latest
          git tag agent-latest ${{ env.commit_part }}
          git tag ${{ env.new_tag }} ${{ env.commit_part }}
          git push origin agent-latest
          git push origin ${{ env.new_tag }}
