name: Add tag for agent
run-name: Add tag for agent
on:
  push:
    branches:
      - refactor
jobs:
  git-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Git status
        run: git status
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "agent-v"
